language: ruby
cache: bundler
sudo: false
rvm: 2.2

branches:
  only:
  - develop

install: script/bootstrap

script:
  - script/build
  - script/test

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  on:
    branch: develop

after_deploy:
  - curl --silent --show-error --data "token=$PUSHOVER_TOKEN&user=$PUSHOVER_USER&title=Script finished: $?&message='Deployment to filipre.github.io succeeded'" https://api.pushover.net/1/messages.json > /dev/null
