title: René's Blog
author: René Filip
email: renefilip@mail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about random stuff.

url: "https://rene.pub"

social_sites:
  twitter: filipre
  github:  filipre
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  #instagram: jekyll
  #linkedin: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

# rss: rss
google_analytics: UA-112738899-1
disqus-shortname: renes-blog

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

permalink: /blog/:title

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"] # disable smart quotes because of KaTeX

plugins:
  - jemoji
  - jekyll-youtube

theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
