baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "René's Blog"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

enableEmoji = true

[menu]
[[menu.main]]
# Unique identifier for a menu item
identifier = "posts"
name = "Posts"
post = ""
pre = "<span data-feather='book'></span>"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<span data-feather='tag'></span>"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contact"
pre = "<span data-feather='mail'></span>"
url = "/contact"
weight = 3

# [[menu.main]]
# identifier = "github"
# url = "https://github.com"
# # We use feather-icons: https://feathericons.com/
# pre = "<span data-feather='github'></span>"
# weight = 4

[params]
# URL for the avatar on homepage
avatarURL = "/images/avatar.png"

# Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
avatarSize = ""

# Description to display on homepage
description = "Random articles and thoughts"

# Accent color is displayed when you hover over <a> tags
accentColor = "#FF4D4D"

# Display "back to top" button on posts
ShowBackToTopButton = true

# You can use this to inject any HTML in the <head> tag.
# Ideal usecase for this is to import custom js/css or add your analytics snippet
customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css" integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV" crossorigin="anonymous">
    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js" integrity="sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8" crossorigin="anonymous"></script>
    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js" integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  '''

# customFooterHTML = '''
#     <small><a href="/impressum">Impressum</a></small>
# '''

# Keywords relevant for SEO
metaKeywords = ["blog", "gokarna", "hugo"]

# If you want to display posts on the homepage, the options are
# "popular" (order posts by weight), "recent" (order posts by date)
# or "" (do not display, default option)
showPostsOnHomePage = "popular"

# Footer text
# footer = "The Marauders"

dateFormat = "2 January, 2006"

# togglePreviousAndNextButtons = "true"

enableRobotsTXT = true
