baseURL = "https://filipre.github.io/" 
defaultContentLanguage = "en" 
enableEmoji = true 
enableRobotsTXT = true
languageCode = "en" 
theme = "gokarna" 
title = "René's Blog" 
relativeURLs = true

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
post = ""
pre = "<span data-feather='book'></span>"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<span data-feather='tag'></span>"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contact"
pre = "<span data-feather='mail'></span>"
url = "/contact"
weight = 3

[params]
avatarURL = "/images/avatar.png"
# Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
avatarSize = ""
description = "Random articles and thoughts"
accentColor = "#E8888A" # "#F2A3B3" # "#e848b0" # "#FF4D4D"
ShowBackToTopButton = true
# KaTeX loading and configuration
customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css" integrity="sha384-5TcZemv2l/9On385z///+d7MSYlvIEw9FuZTIdZ14vJLqWphw7e7ZPuOiCHJcFCP" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js" integrity="sha384-cMkvdD8LoxVzGF/RPUKAcvmm49FQ0oxwDF3BGKtDXcEc+T1b2N+teh/OJfpU0jr6" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js" integrity="sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          throwOnError : false
        });
      });
    </script>
'''
metaKeywords = ["blog", "gokarna", "hugo"]
showPostsOnHomePage = "popular"
numberPostsOnHomePage = 10
footer = "René Filip"
dateFormat = "2 January, 2006"
socialIcons = [
  {name = "linkedin", url = "https://www.linkedin.com/in/rene-filip/"},
  {name = "github", url = "https://github.com/filipre"},
  {name = "email", url = "mailto:renefilip[at]mail[dot]com"},
]

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files