#!/bin/sh
curl --silent --show-error --data "token=$PUSHOVER_TOKEN&user=$PUSHOVER_USER&title='Deployment succeeded'&message='Deployment to filipre.github.io succeeded'" https://api.pushover.net/1/messages.json
